# These are supported funding model platforms
github: addispupi
# You can also add platforms like Patreon or Buy Me a Coffee if you use them:
patreon: addispupi
# custom: https://addispupi.com/support